#include "draw.h"
#include "gba.h"

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
// #include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);

// This function will be used to draw everything about the app
// including the background and whatnot.
void fullDrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    switch(state->location) {
        case HOME:
            drawRectDMA(0, 0, 240, 160, BLACK);
            if (state->locEventCount >= 10) {
                state->mc.oam->attr1 = state->mc.x | MC1_SPRITE_SIZE;
                drawRectDMA(0, 40, 240, 2, CYAN);
            }
            drawSprites();
            break;
        case RIDDLE_ROOM:
            drawFullScreenImageDMA((u16*) riddleRoom);
            state->mc.oam->attr1 = state->mc.x | MC1_SPRITE_SIZE;
            break;
        case OUTDOORS:
            // state->mc.y = 100;
            drawFullScreenImageDMA((u16 *) outside);
    }
    drawString(2, 2, "Score:", MAGENTA);
}

// This function will be used to undraw (i.e. erase) things that might
// move in a frame. E.g. in a Snake game, erase the Snake, the food & the score.
void undrawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    UNUSED(state);
}

void drawHOMEAppState(AppState *state) {
    switch (state->locEventCount) {
        case 0:
            break;
        case 1:
            drawString(155, 150, "(<B> for help)", WHITE);
            break;
        case 2:
            drawString(155, 150, "(<B> for help)", BLACK);
            drawCenteredString(0, 150, 240, 10, "Welcome to the The TRIALS betA version", CYAN);
            break;
        case 3:
            drawCenteredString(0, 150, 240, 10, "Welcome to the The TRIALS betA version", BLACK);
            drawCenteredString(0, 150, 240, 10, "This is the trial system of The TRIALS", CYAN);
            drawCenteredString(0, 140, 240, 10, "Pressing <SELECT> will reset the system", GRAY);
            break;
        case 4:
            drawCenteredString(0, 140, 240, 10, "Pressing <SELECT> will reset the system", BLACK);
            drawCenteredString(0, 150, 240, 10, "This is the trial system of The TRIALS", BLACK);
            drawCenteredString(0, 140, 240, 10, "YOU HAVE BEEN WARNED", GRAY);
            drawCenteredString(0, 150, 240, 10, "DO NOT PRESS <L> AFTER THIS", RED);
            break;
        case 5:
            drawCenteredString(0, 140, 240, 10, "YOU HAVE BEEN WARNED", BLACK);
            drawCenteredString(0, 150, 240, 10, "DO NOT PRESS <L> AFTER THIS", BLACK);
            drawCenteredString(0, 150, 240, 10, "Tutorial: Press <A> to swing", WHITE);
            break;
        case 6:
            drawCenteredString(0, 150, 240, 10, "Tutorial: Press <A> to swing", BLACK);
            drawCenteredString(0, 135, 240, 10, "Tutorial: Press <R> to shoot", WHITE);
            drawCenteredString(0, 150, 240, 10, "Note you only have 1 replenishing arrow", WHITE);
            break;
        case 7:
            drawCenteredString(0, 135, 240, 10, "Tutorial: Press <R> to shoot", BLACK);
            drawCenteredString(0, 150, 240, 10, "Note you only have 1 replenishing arrow", BLACK);
            drawCenteredString(0, 150, 240, 10, "PROCEED to the FIRST TRIAL -->", YELLOW);
            drawImageTransparent(RINGX, RINGY, RING1_WIDTH, RING1_HEIGHT, IMAGES_TRANSPARENT, (u16 *) ring1);
            break;
        case 8:
            drawRectDMA(RINGX, RINGY, RING1_WIDTH, RING1_HEIGHT, BLACK);
            break;
        default:
            break;
    }
    if (state->locEventCount > 10 && !state->showQuestion) {
        drawRectDMA(RIDDLEX, RIDDLEY, Q1_WIDTH, Q1_HEIGHT, BLACK);
        drawRectDMA(0, 40, 240, 2, CYAN);
    }
    if (state->locEventCount >= 10) {
        drawString(RIDDLEX + 125, RIDDLEY + 10, state->ans, YELLOW);
        switch (state->ansIndex) {
            case 0:
                drawString(RIDDLEX + 125, RIDDLEY + 11, "_", YELLOW);
                break;
            case 1:
                drawString(RIDDLEX + 125, RIDDLEY + 11, " _", YELLOW);
                break;
            case 2:
                drawString(RIDDLEX + 125, RIDDLEY + 11, "  _", YELLOW);
                break;
            case 3:
                drawString(RIDDLEX + 125, RIDDLEY + 11, "   _", YELLOW);
                break;
        }
    }
    if (state->s0.isActive) {
        drawImageDMA(S0X, S0Y, SELECT0_WIDTH, SELECT0_HEIGHT, (u16 *) select0);
    }
    if (state->s1.isActive) {
        drawImageDMA(S1X, S1Y, SELECT1_WIDTH, SELECT1_HEIGHT, (u16 *) select1);
    }
    if (state->s2.isActive) {
        drawImageDMA(S2X, S2Y, SELECT2_WIDTH, SELECT2_HEIGHT, (u16 *) select2);
    }
}

void drawRIDDLE_ROOMAppState(AppState *state) {
    switch (state->locEventCount) {
        case 10:
            drawImageDMA(ENTERX, ENTERY, ENTER_WIDTH, ENTER_HEIGHT, (u16 *) unactive);
            break;
        case 11:
            drawCenteredString(0, 12, 240, 10, "Solve the riddle (<B> to SHOW)", GREEN);
            break;
        case 12:
            break;
        default:
            break;
    }
    if (state->locEventCount >= 100) {
        drawCenteredString(0, 150, 240, 10, "CORRECT! TRIAL 2 Coming SOON", YELLOW);
    }
    if (state->enter.isActive) {
        drawImageDMA(ENTERX, ENTERY, ENTER_WIDTH, ENTER_HEIGHT, (u16 *) enter);
    }
    if (state->clear.isActive) {
        drawImageDMA(CLEARX, CLEARY, CLEAR_WIDTH, CLEAR_HEIGHT, (u16 *) clear);
    }
    if (!state->mc.hasRing) {
        drawImageTransparent(RINGX, RINGY, RING2_WIDTH, RING2_HEIGHT, IMAGES_TRANSPARENT, (u16 *) ring2);
    } else {
        drawImageSpliceDMA(RINGX, RINGY, RINGX, RINGY, RING1_WIDTH, RING1_HEIGHT, 240, (u16 *) riddleRoom);
    }
    if (state->locEventCount > 11 && !state->showQuestion) {
        drawImageSpliceDMA(RIDDLEX, RIDDLEY, RIDDLEX, RIDDLEY, Q1_WIDTH, Q1_HEIGHT, 240, (u16 *) riddleRoom);
    }
}

void drawOUTDOORSAppState(AppState *state) {
    if (state->s3.isActive) {
        drawImageDMA(S3X, S3Y, SELECT3_WIDTH, SELECT3_HEIGHT, (u16 *) select3);
    }
    if (state->locEventCount > 11 && !state->showQuestion) {
        drawImageSpliceDMA(RIDDLEX, RIDDLEY, RIDDLEX, RIDDLEY, Q1_WIDTH, Q1_HEIGHT, 240, (u16 *) outside);
    }
    if (state->help) {
        drawString(0, 114, "Autobiographical Numbers", BLACK);
        drawString(0, 126, "A number N where the 1st digit", BLACK);
        drawString(0, 138, "counts how many 0s there are, the", BLACK);
        drawString(0, 150, "2nd digit counts how many 1s ... ", BLACK);
    }
}

// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
    // TA-TODO: IMPLEMENT.
    if (state->location != state->lastLocation) {
        fullDrawAppState(state);
        state->lastLocation = state->location;
        state->stateUpdate = true;
    }

    if (state->stateUpdate) {
        char score[5];
        sprintf(score, "%d", state->locEventCount + state->mc.ringCount);

        switch(state->location) {
            case HOME:
                drawRectDMA(38, 2, 20, 10, BLACK);
                drawHOMEAppState(state);
                break;
            case RIDDLE_ROOM:
                drawImageSpliceDMA(38, 2, 38, 2, 20, 10, 240, (u16 *) riddleRoom);
                drawRIDDLE_ROOMAppState(state);
                break;
            case OUTDOORS:
                drawImageSpliceDMA(38, 2, 38, 2, 20, 10, 240, (u16 *) outside);
                drawOUTDOORSAppState(state);
                break;
        }
        drawString(38, 2, score, YELLOW);
        state->stateUpdate = false;
    }
    if (state->locEventCount > 10 && state->showQuestion) {
        drawImageDMA(RIDDLEX, RIDDLEY, Q1_WIDTH, Q1_HEIGHT, (u16 *) q1);
        drawString(RIDDLEX + 125, RIDDLEY + 10, state->ans, YELLOW);
    }
    
    drawSprites();
    //for debugging
    // char a[20];
    // sprintf(a, "%d, %d, %d", state->locEventCount, state->mc.x, (ISCOLLIDE(state->arrow.x, state->arrow.y, ARROW_HW, ARROW_HW, ENTERX, ENTERY, ENTER_WIDTH, ENTER_HEIGHT) || 
    //     (ISCOLLIDE(state->mc.x, state->mc.y, 33, 33, ENTERX, ENTERY, ENTER_WIDTH, ENTER_HEIGHT) && state->mc.a == SWING && state->mc.animateC == MC_SWING_LENGTH - 1)));
    // drawRectDMA(0, 0, 100, 10, BLACK);
    // drawString(0, 0, a, WHITE);
}
